apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-app-deployment
  labels:
    app: k8s-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django-app
  template:
    metadata:
      labels:
        app: django-app
    spec:
      containers:
        - name: django-app-web
          image: alex662/django_project:latest
          ports:
            - containerPort: 80
          env:
            - name: DEBUG
              value: 'True'
            - name: ALLOWED_HOSTS
              value: '192.168.39.21'
            - name: DATABASE_URL
              value: 'postgres://test_k8s:OwOtBep9Frut@192.168.0.10:5432/test_k8s'



