apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-app-deployment
  labels:
    app: k8s-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django-app
  template:
    metadata:
      labels:
        app: django-app
    spec:
      containers:
        - name: django-app-web
          image: alex662/django_project:latest
          ports:
            - containerPort: 80
          envFrom:
            - secretRef:
                name: django-app-secret



