apiVersion: batch/v1
kind: CronJob
metadata:
  name: clear-sessions-job
spec:
  schedule: "0 0 * * 0"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: clear-sessions-container
              image: alex662/django_app:6.0
              imagePullPolicy: IfNotPresent
              command: ["python", "manage.py", "clearsessions"]
              envFrom:
                - secretRef:
                    name: django-app-secret
          restartPolicy: OnFailure



